# Generated by Django 3.2.7 on 2021-09-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
    ]
