# Generated by Django 3.2.7 on 2021-10-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='card',
        ),
    ]
