# Generated by Django 3.2.7 on 2021-10-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position_secondary',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
