# Generated by Django 3.2.7 on 2021-09-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('type', models.CharField(choices=[('turf', 'газон'), ('grass', 'трава'), ('indoor', 'в помещении'), ('sand', 'песок'), ('beach', 'пляж')], max_length=20)),
                ('service', models.JSONField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('location', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/field_images')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.field')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, max_digits=7)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('turf', 'газон'), ('grass', 'трава'), ('indoor', 'в помещении'), ('sand', 'песок'), ('beach', 'пляж')], max_length=100)),
                ('match_type', models.CharField(choices=[('friendly', 'товарищеский'), ('competitive', 'соревновательный')], max_length=100)),
                ('need_players', models.IntegerField(default=2)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image', models.ImageField(upload_to='media/game_detail')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('played_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
