# Generated by Django 3.2.7 on 2021-09-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='service',
            field=models.CharField(max_length=1000),
        ),
    ]
