# Generated by Django 3.2.7 on 2021-10-01 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fields', '0003_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='played_users',
            field=models.ManyToManyField(related_name='played_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
