# Generated by Django 3.2.7 on 2021-09-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
